/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { Survivor, SurvivorInterface } from '../Survivor';

const _abi = [
  {
    inputs: [],
    name: 'currentWinner',
    outputs: [
      {
        internalType: 'string',
        name: '',
        type: 'string',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'currentWinnerScore',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'guessed',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: '_name',
        type: 'string',
      },
      {
        internalType: 'uint256',
        name: '_guess',
        type: 'uint256',
      },
    ],
    name: 'playGame',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

export class Survivor__factory {
  static readonly abi = _abi;
  static createInterface(): SurvivorInterface {
    return new utils.Interface(_abi) as SurvivorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): Survivor {
    return new Contract(address, _abi, signerOrProvider) as Survivor;
  }
}
