/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Survivor } from './Survivor';
export * as factories from './factories';
export { Survivor__factory } from './factories/Survivor__factory';
